version: 2.1

jobs:
  build:
    docker:
      - image: nixos/nix:2.3
    steps:
      - checkout
      - run:
          name: Install build script
          command: nix-env -f default.nix -iA build
      - run:
          name: Build docs
          command: postgrest-docs-build

  spellcheck:
    docker:
      - image: nixos/nix:2.3
    steps:
      - checkout
      - run:
          name: Install spellcheck script
          command: nix-env -f default.nix -iA spellcheck
      - run:
          name: Run spellcheck
          command: postgrest-docs-spellcheck

  linkcheck:
    docker:
      - image: nixos/nix:2.3
    steps:
      - checkout
      - run:
          name: Install linkcheck script
          command: nix-env -f default.nix -iA linkcheck
      - run:
          name: Run linkcheck
          command: postgrest-docs-linkcheck

workflows:
  check:
    jobs:
      - build
      - spellcheck
      - linkcheck
