name: CI

on:
  push:
    branches:
    - main
    - v*
  pull_request:
    branches:
    - main
    - v*

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - run: nix-env -f default.nix -iA build
    - run: postgrest-docs-build
    - run: git diff --exit-code HEAD locales || echo "Please commit changes to the locales/ folder after running postgrest-docs-build."

  spellcheck:
    name: Run spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - run: nix-env -f default.nix -iA spellcheck
    - run: postgrest-docs-spellcheck

  dictcheck:
    name: Run dictcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - run: nix-env -f default.nix -iA dictcheck
      - run: postgrest-docs-dictcheck

  linkcheck:
    name: Run linkcheck
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - run: nix-env -f default.nix -iA linkcheck
    - run: postgrest-docs-linkcheck
    
